
export const vmieData = {    
    websitePages: [
        {
            id: "Welcome",
            title: "Our Mission",
            contentUrl: "./content/index.txt",
            url: "site",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Compatibility",
            title: "Compatibility check",
            contentUrl: "./content/compatibility.txt",
            url: "site",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Security",
            title: "Information and Security",
            contentUrl: "./content/security.txt",
            url: "site",
            isSelected: false,
        },
        {
            id: "Architecture",
            title: "Software Architecture",
            contentUrl: "./content/architecture.txt",
            url: "site",
            isSelected: false,
        },
        {
            id: "Join",
            title: "Join our Data Exchange Programm",
            contentUrl: "./content/applications.txt",
            url: "site",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Board",
            title:  "Contributions",
            contentUrl: "./content/decisions.txt",
            url: "board",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Builder",
            title:  "Logic builder",
            contentUrl: "./content/builder.txt",
            url: "builder",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Jobs",
            title:  "Jobs",
            contentUrl: "./content/feature-jobs.txt",
            url: "jobs",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Chat",
            title:  "Chat",
            contentUrl: "./content/chat.txt",
            url: "chat",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Developers",
            title:  "Developers (project)",
            contentUrl: "./content/developers.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Repos",
            title:  "Other Repos",
            contentUrl: "./content/feature-repos.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "PetId",
            title:  "PetId (project)",
            contentUrl: "./content/petId.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Exchange",
            title:  "Exchange (project)",
            contentUrl: "./content/exchangeProfiles.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Developer",
            title:  "Developer Profile",
            contentUrl: "./content/developer.txt",
            url: "board",
            hideOnMobile: true,
            isSelected: false,
        },
        {
            id: "Tasks Management",
            title:  "Tasks Management",
            contentUrl: "./content/feature-tasks-management.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Mailing System",
            title:  "Mailing System",
            contentUrl: "./content/feature-mailing-system.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "GDPR",
            title:  "GDPR",
            contentUrl: "./content/feature-gdpr.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Website",
            title:  "Website",
            contentUrl: "./content/feature-website.txt",
            url: "board",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "News",
            title:  "News",
            contentUrl: "./content/feature-news.txt",
            url: "news",
            hideOnMobile: true,
            alwaysHide: true,
            isSelected: false,
        },
        {
            id: "Privacy",
            title: "Terms & Privacy",
            contentUrl: "./content/privacy.txt",
            url: "site",
            isSelected: false,
        },
    ],
}

export const vmieService = {
}

export default {
    vmieService,
    vmieData
}
